dns/py-dnspython: Update to 2.1.0
Update to 2.1.0, which fixes runtime error "AttributeError: module
'base64' has no attribute 'decodestring'" with python 3.9.

Changes: https://dnspython.readthedocs.io/en/stable/whatsnew.html